=== EdgeCaseBerg/scala-xsd-validation/src/main/resources/box.xsd
<xs:schema xmlns:xs='http://www.w3.org/2001/XMLSchema'>
  <xs:element name="Boxes">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Box" minOccurs='0' maxOccurs='unbounded'/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="Box">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Id" minOccurs='1' maxOccurs='1'/>
        <xs:element ref="Name" minOccurs='1' maxOccurs='1'/>
        <xs:element ref="Contains" minOccurs='1' maxOccurs='1'/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="Name" type='xs:string'/>
  <xs:element name="Id" type='xs:integer'/>
  <xs:element name="Contains">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="BoxedItem" minOccurs='0' maxOccurs='unbounded'/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="BoxedItem" type='xs:string'/>
</xs:schema>

=== EdgeCaseBerg/scala-xsd-validation/src/test/resources/box-sample.xml
<?xml version="1.0" encoding="UTF-8"?>
<Boxes 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/EdgeCaseBerg/scala-xsd-validation/master/src/main/resources/box.xsd"
>
	<Box>
		<Id>0</Id>
		<Name>First Box</Name>
		<Contains>
			<BoxedItem>Thing 1</BoxedItem>
			<BoxedItem>Thing 2</BoxedItem>
		</Contains>
	</Box>
	<Box>
		<Id>2</Id>
		<Name>Second Box</Name>
		<Contains>
			<BoxedItem>Second Thing 1</BoxedItem>
			<BoxedItem>Second Thing 2</BoxedItem>
		</Contains>
	</Box>
</Boxes>
