=== EdgeCaseBerg/scala-xsd-validation/src/main/resources/tree.xsd
<xs:schema xmlns:xs='http://www.w3.org/2001/XMLSchema'>
  <xs:element name="Forest">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Tree" minOccurs='0' maxOccurs='unbounded'/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="Tree">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="State" minOccurs='0' maxOccurs='1'/>
        <xs:element ref="Leaves" minOccurs='1' maxOccurs='1'/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:simpleType name="TreeState" final="restriction" >
    <xs:restriction base="xs:string">
        <xs:enumeration value="ALIVE" />
        <xs:enumeration value="DEAD" />
    </xs:restriction>
  </xs:simpleType>

  <xs:element name="State" type='TreeState'/>
  <xs:element name="Leaves">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Leaf" minOccurs='0' maxOccurs='unbounded'/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="Leaf">
    <xs:complexType>
      <xs:attribute name="color" type="xs:string"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== EdgeCaseBerg/scala-xsd-validation/src/test/resources/tree-sample.xml
<?xml version="1.0" encoding="UTF-8"?>
<Forest 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/EdgeCaseBerg/scala-xsd-validation/master/src/main/resources/tree.xsd"
>
	<Tree>
		<State>ALIVE</State>		
		<Leaves>
			<Leaf color="Green"/>
			<Leaf color="Yellow"/>
		</Leaves>
	</Tree>
	<Tree>
		<!-- No State Element, will have default -->
		<Leaves>
			<Leaf color="Brown"/>
			<Leaf color="Grey"/>
			<Leaf color="Gray"/>
		</Leaves>
	</Tree>
</Forest>
